// <auto-generated />
using System;
using AuctionService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuctionService.Infrastructure.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    partial class AuctionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuctionService.Core.Entities.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("StartingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Auctions_CategoryId");

                    b.HasIndex("EndTime")
                        .HasDatabaseName("IX_Auctions_EndTime");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_Auctions_UserId_CreatedAt");

                    b.ToTable("Auctions", (string)null);
                });

            modelBuilder.Entity("AuctionService.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Categories_Name_Unique");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "電子產品"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "家具"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "收藏品"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "藝術品"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "服飾配件"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsActive = true,
                            Name = "書籍"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            IsActive = true,
                            Name = "運動用品"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 99,
                            IsActive = true,
                            Name = "其他"
                        });
                });

            modelBuilder.Entity("AuctionService.Core.Entities.Follow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId")
                        .HasDatabaseName("IX_Follows_AuctionId");

                    b.HasIndex("UserId", "AuctionId")
                        .IsUnique()
                        .HasDatabaseName("IX_Follows_UserId_AuctionId_Unique");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_Follows_UserId_CreatedAt");

                    b.ToTable("Follows", (string)null);
                });

            modelBuilder.Entity("AuctionService.Core.Entities.ResponseCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MessageZhTw")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Code");

                    b.ToTable("ResponseCodes", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "AUCTION_CREATED",
                            Category = "Success",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MessageEn = "Auction created successfully",
                            MessageZhTw = "商品建立成功",
                            Name = "商品已建立",
                            Severity = "Info"
                        },
                        new
                        {
                            Code = "AUCTION_UPDATED",
                            Category = "Success",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MessageEn = "Auction updated successfully",
                            MessageZhTw = "商品更新成功",
                            Name = "商品已更新",
                            Severity = "Info"
                        },
                        new
                        {
                            Code = "AUCTION_DELETED",
                            Category = "Success",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MessageEn = "Auction deleted successfully",
                            MessageZhTw = "商品刪除成功",
                            Name = "商品已刪除",
                            Severity = "Info"
                        },
                        new
                        {
                            Code = "AUCTION_NOT_FOUND",
                            Category = "ClientError",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MessageEn = "Auction not found",
                            MessageZhTw = "查無此商品",
                            Name = "商品不存在",
                            Severity = "Warning"
                        },
                        new
                        {
                            Code = "AUCTION_INVALID_END_TIME",
                            Category = "ClientError",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MessageEn = "End time must be at least 1 hour from now",
                            MessageZhTw = "結束時間必須至少在 1 小時之後",
                            Name = "結束時間無效",
                            Severity = "Warning"
                        },
                        new
                        {
                            Code = "AUCTION_HAS_BIDS",
                            Category = "ClientError",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MessageEn = "Cannot edit or delete auction with existing bids",
                            MessageZhTw = "已有出價的商品無法編輯或刪除",
                            Name = "商品已有出價",
                            Severity = "Warning"
                        },
                        new
                        {
                            Code = "AUCTION_UNAUTHORIZED",
                            Category = "ClientError",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MessageEn = "Unauthorized to access this auction",
                            MessageZhTw = "無權限操作此商品",
                            Name = "無權限操作",
                            Severity = "Error"
                        },
                        new
                        {
                            Code = "FOLLOW_ALREADY_EXISTS",
                            Category = "ClientError",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MessageEn = "Already following this auction",
                            MessageZhTw = "已在追蹤清單中",
                            Name = "已追蹤",
                            Severity = "Info"
                        },
                        new
                        {
                            Code = "FOLLOW_OWN_AUCTION",
                            Category = "ClientError",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MessageEn = "Cannot follow your own auction",
                            MessageZhTw = "無法追蹤自己的商品",
                            Name = "無法追蹤自己的商品",
                            Severity = "Warning"
                        },
                        new
                        {
                            Code = "FOLLOW_LIMIT_EXCEEDED",
                            Category = "ClientError",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MessageEn = "Follow limit exceeded (500)",
                            MessageZhTw = "追蹤商品數量已達上限 (500)",
                            Name = "追蹤數量超過限制",
                            Severity = "Warning"
                        },
                        new
                        {
                            Code = "INTERNAL_SERVER_ERROR",
                            Category = "ServerError",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MessageEn = "Internal server error, please try again later",
                            MessageZhTw = "伺服器發生錯誤，請稍後再試",
                            Name = "內部伺服器錯誤",
                            Severity = "Error"
                        },
                        new
                        {
                            Code = "BIDDING_SERVICE_UNAVAILABLE",
                            Category = "ServerError",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MessageEn = "Bidding service is unavailable",
                            MessageZhTw = "競標服務暫時無法使用",
                            Name = "競標服務無法使用",
                            Severity = "Error"
                        });
                });

            modelBuilder.Entity("AuctionService.Core.Entities.Auction", b =>
                {
                    b.HasOne("AuctionService.Core.Entities.Category", "Category")
                        .WithMany("Auctions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AuctionService.Core.Entities.Follow", b =>
                {
                    b.HasOne("AuctionService.Core.Entities.Auction", "Auction")
                        .WithMany("Follows")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("AuctionService.Core.Entities.Auction", b =>
                {
                    b.Navigation("Follows");
                });

            modelBuilder.Entity("AuctionService.Core.Entities.Category", b =>
                {
                    b.Navigation("Auctions");
                });
#pragma warning restore 612, 618
        }
    }
}
